### ISSUE TITLE
Update Apple Silicon installation instructions

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-docs#11]
Once https://github.com/conda-forge/ambertools-feedstock/pull/116 is merged (should be a matter of hours) our stack is mostly or completely available on Apple Silicon. This would be a good time to update the centralized installation instructions

**Comment by mikemhenry** [comment]
I can confirm that installing on an arm64 box that conda didn't complain about any other deps missing.

**Comment by mattwthompson** [comment]
To be slightly less ambiguous, I hem and haw because I'm not sure about what else the likes of BespokeFit also needs. The toolkit and ~90% of use cases I'm aware of should be golden

**Comment by mikemhenry** [comment]
Ah sorry! I thought I was on the openff-toolkit repo :upside_down_face:

**Comment by Yoshanuikabundi** [comment]
Oh that's awesome news! 

If we update the installation instructions, we should also update `run_notebook.sh` to detect ISA (now it defaults to x86_64), so this issue can track both of those problems.

It looks like [Psi4](https://anaconda.org/conda-forge/psi4/files) now has ARM builds for MacOS on Conda Forge (!!!), so we might be good on the BespokeFit side of things too.

Looks like [GROMACS is out on Forge](https://anaconda.org/conda-forge/gromacs/files) - I thought it was just on Bioconda. But I must be way out of date on that because it hasn't been updated on bioconda in nearly two years. So that's good news. Unfortunately they don't seem to have an `osx-arm64` build, so it might be worth waiting.

**Comment by mikemhenry** [comment]
How big is the demand for an `osx-arm64` of GROMACS?

**Comment by mattwthompson** [comment]
Marginal for me, and only affecting development. It's the only thing affecting me from switching architectures in [one of my development environments](https://github.com/openforcefield/openff-interchange/blob/f431a487b3213038356c083d0a9f52de9a60e56c/devtools/conda-envs/dev_env.yaml).

I don't think there's much of a demand in terms of production-scale simulations. I don't think any of our partners  or much of our academic user base use non-x86 architecture on clusters. I'm [not sure if it's optimized for performance](https://manual.gromacs.org/documentation/nightly/release-notes/2023/major/portability.html#initial-support-for-apple-silicon-gpus), though the GROMACS devs historically value portability at the level of things being runnable.

I wouldn't stand in your way if you choose to tackle it, but I also wouldn't ask for you work on it instead of something actually important 🙃

**Comment by Yoshanuikabundi** [comment]
Yeah it definitely feels like a nice-to-have to me more than something essential. Our examples use it though so they'll have to stay on x86_64 until it's supported. I'm a little surprised there isn't more demand for it, GROMACS must build on ARM right?

**Comment by mattwthompson** [comment]
Following your links and some other searches, it seems like it builds fine natively (which `conda-forge` can't do). I think it's common enough for people to roll their own builds that it's not critical to support

**Comment by mattwthompson** [comment]
Three months later,

* GROMACS: The bot [is trying](https://github.com/conda-forge/gromacs-feedstock/pull/21), though progress appears slow. This isn't needed for any core examples
* NAGL: I don't know what all is needed, but I'm not able to install it locally
* BespokeFit: I don't know
